--- 
abstract: A lightning talk about the C<split //> optimization in perl 5.10
author: Ævar Arnfjörð Bjarmason <avar@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Talk-NothingIsFaster510
no_index: 
  directory: 
    - inc
    - t
tests: t/*.t
version: 0.01
